"""Constants for PNZEO Camera integration."""

DOMAIN = "pnzeo_camera"
CONF_DEVICE_ID = "device_id"
CONF_RTSP_PORT = "rtsp_port"

# Defaults
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "8888"
DEFAULT_RTSP_PORT = 554
DEFAULT_PPPP_PORT = 32108

# RTSP paths
RTSP_MAIN_STREAM = "/11"
RTSP_SUB_STREAM = "/12"

# --- PPPP Protocol Ports ---
# Camera LAN discovery port (DH protocol, magic 44 48 01 01)
PPPP_PORT_DH_LAN = 8600
# Standard PPPP LAN discovery port (magic f1 30 00 00)
PPPP_PORT_STANDARD = 32108
# Cloud P2P relay port
PPPP_PORT_CLOUD = 32100

# DH protocol magic bytes for LAN discovery on port 8600
DH_MAGIC = b"\x44\x48\x01\x01"
# Standard PPPP LAN search magic
PPPP_LAN_SEARCH_MAGIC = b"\xf1\x30\x00\x00"

# Cloud P2P server list (tried in order)
CLOUD_P2P_SERVERS = [
    ("54.191.3.239", PPPP_PORT_CLOUD),     # AWS Oregon
    ("54.186.48.247", PPPP_PORT_CLOUD),     # AWS Oregon
    ("182.92.131.196", PPPP_PORT_CLOUD),    # China
]

# --- F1xx Message Types (PPPP signaling layer) ---
# Two-byte big-endian message IDs used in the P2P handshake
MSG_HELLO = 0xF100          # Client -> Server, 4 bytes
MSG_HELLO_ACK = 0xF101      # Server -> Client, 20 bytes
MSG_P2P_CONNECT = 0xF120    # Client -> Server, 40 bytes (PPRT + UID)
MSG_P2P_READY = 0xF121      # Server -> Client, 8 bytes
MSG_DRW_RESPONSE = 0xF140   # Server -> Client, 20 bytes (camera IPs)
MSG_RELAY_REQ = 0xF167      # Client -> Server, 24 bytes (UID)
MSG_PUNCH = 0xF180          # 44 bytes

# PPPP Connection States
PPPP_STATUS_UNKNOWN = -1
PPPP_STATUS_CONNECTING = 0
PPPP_STATUS_INITIALING = 1
PPPP_STATUS_ONLINE = 2
PPPP_STATUS_CONNECT_FAILED = 3
PPPP_STATUS_DISCONNECT = 4
PPPP_STATUS_INVALID_ID = 5
PPPP_STATUS_DEVICE_OFFLINE = 6
PPPP_STATUS_TIMEOUT = 7
PPPP_STATUS_ERROR = 8
PPPP_STATUS_MAX_CONNECTIONS = 9
PPPP_STATUS_AUTHENTICATED = 10

# PPPP Packet Types (legacy single-byte, used after connection established)
PKT_HELLO = 0xF1
PKT_HELLO_ACK = 0xF1  # same type, response
PKT_LAN_SEARCH = 0x67
PKT_LAN_SEARCH_ACK = 0x68
PKT_PUNCH_PKT = 0x41
PKT_P2P_RDY = 0x42
PKT_DRW = 0xD0  # data packet
PKT_DRW_ACK = 0xD1
PKT_ALIVE = 0xE0
PKT_ALIVE_ACK = 0xE1
PKT_CLOSE = 0xF0
PKT_MGM = 0xF4  # management

# PPPP I/O Channel Types
CH_CMD = 0    # command channel
CH_VIDEO = 1  # video channel
CH_AUDIO = 2  # audio channel
CH_TALK = 3   # talk channel

# Message Types (MSG_TYPE from ContentCommon.java)
MSG_GET_CAMERA_PARAMS = 2
MSG_DECODER_CONTROL = 3
MSG_GET_PARAMS = 4
MSG_SNAPSHOT = 5
MSG_CAMERA_CONTROL = 6
MSG_SET_NETWORK = 7
MSG_REBOOT = 8
MSG_FACTORY_RESET = 9
MSG_SET_USER = 10
MSG_SET_WIFI = 11
MSG_SET_DATETIME = 12
MSG_GET_STATUS = 13
MSG_GET_PTZ_PARAMS = 14
MSG_SET_DDNS = 15
MSG_SET_MAIL = 16
MSG_SET_FTP = 17
MSG_SET_ALARM = 18
MSG_SET_PTZ = 19
MSG_WIFI_SCAN = 20
MSG_GET_ALARM_LOG = 21
MSG_GET_RECORD = 22
MSG_GET_RECORD_FILE = 23
MSG_SET_RECORD_SCH = 28
MSG_CLEAR_ALARM_LOG = 29
MSG_WIFI_PARAMS = 31
MSG_MAIL_PARAMS = 32
MSG_FTP_PARAMS = 33
MSG_NETWORK_PARAMS = 34
MSG_USER_INFO = 35
MSG_DDNS_PARAMS = 36
MSG_DATETIME_PARAMS = 37
MSG_ALARM_PARAMS = 38
MSG_SET_DEVNAME = 39
MSG_SET_AP = 52
MSG_GET_AP = 53
MSG_GET_NETWORK = 65
MSG_GET_USER_INFO = 66
MSG_GET_WIFI = 67
MSG_GET_FTP = 68
MSG_GET_EMAIL = 69
MSG_GET_DDNS = 70
MSG_GET_TIME = 71
MSG_GET_ALARM_PARAM = 72
MSG_FORMAT_SD = 73
MSG_GET_CAPABILITY = 74
MSG_SET_REC_MODE = 80
MSG_GET_REC_MODE = 81
MSG_SET_MOBILE_TIME = 82
MSG_GET_REC_CALENDAR = 83
MSG_UNMOUNT_SD = 84
MSG_GET_ALARM_EX = 85
MSG_SET_ALARM_EX = 86
MSG_GET_SD_REC_EX = 87
MSG_SET_SD_REC_EX = 88
MSG_CHECK_USER_CAPABILITY = 96
MSG_SET_FCM_PUSH = 97
MSG_GET_VOICE = 99

# Camera Control Commands (RTCameraControl cmdType)
CMD_SET_RESOLUTION = 0
CMD_SET_BRIGHTNESS = 1
CMD_SET_CONTRAST = 2
CMD_SET_POWER_FREQ = 3
CMD_SET_MIRROR = 5
CMD_SET_LIGHT = 14
CMD_SET_LED = 15

# PTZ Commands (RTPTZControl ptzCmd)
PTZ_UP = 0
PTZ_UP_STOP = 1
PTZ_DOWN = 2
PTZ_DOWN_STOP = 3
PTZ_LEFT = 4
PTZ_LEFT_STOP = 5
PTZ_RIGHT = 6
PTZ_RIGHT_STOP = 7
PTZ_CENTER = 25
PTZ_PATROL_UD = 26
PTZ_PATROL_UD_STOP = 27
PTZ_PATROL_LR = 28
PTZ_PATROL_LR_STOP = 29
PTZ_ZOOM_IN = 99
PTZ_ZOOM_OUT = 100
PTZ_FOCUS_IN = 101
PTZ_FOCUS_OUT = 102

# PTZ Preset (set=even 30-60, run=odd 31-61)
PTZ_PRESET_SET_BASE = 30
PTZ_PRESET_RUN_BASE = 31

# Mirror modes
MIRROR_NORMAL = 0
MIRROR_VERTICAL = 1
MIRROR_HORIZONTAL = 2
MIRROR_BOTH = 3

# Alarm types
ALARM_MOTION = 1
ALARM_GPIO = 2
ALARM_SCHEDULE = 3
ALARM_CONTROL = 4
ALARM_HUMIDITY = 5
ALARM_PM25 = 6
ALARM_SMOKE = 7
ALARM_SOUND = 8
ALARM_MOTION_EX = 17
ALARM_GPIO_EX = 18
ALARM_VOLTAGE = 19
ALARM_SMD = 20

# Stream types
STREAM_H264_MAIN = 0
STREAM_H264_SUB = 1
STREAM_MJPEG_SUB = 3

# Resolution
RES_640P = 0
RES_720P = 1
RES_1080P = 2
RES_2K = 3
RES_4K = 4

RESOLUTION_MAP = {
    RES_640P: "640p",
    RES_720P: "720p",
    RES_1080P: "1080p",
    RES_2K: "2K",
    RES_4K: "4K",
}

MIRROR_MAP = {
    MIRROR_NORMAL: "Normal",
    MIRROR_VERTICAL: "Vertical flip",
    MIRROR_HORIZONTAL: "Horizontal flip",
    MIRROR_BOTH: "Both",
}
